name: Run Python Tests
on: 
    push:
        branches:
            -main
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: action/checkout@v2
            - name: Install Python
              uses: action/setup-python@v1
              with:
                python-version: 3.12.9
            - name: Install Dependencies
              run: |
                python -m pip install --upgrade pip
                pip install pytest
                pip install -r equirements.txt
            - name: Run tests with pytest
              run: pytest